name: release

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: ${{ github.event.release.target_commitish }}
        persist-credentials: false

    - name: Install Socket Firewall
      uses: SocketDev/action@ba6de6cc0565af1f42295590380973573297e31f # v1.3.2
      with:
        mode: firewall-free
        firewall-version: "1.15.0"

    - name: Use Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 24
        package-manager-cache: false

    - name: Enable Corepack
      run: |
        unset HTTP_PROXY HTTPS_PROXY http_proxy https_proxy ALL_PROXY all_proxy
        corepack enable && corepack prepare

    - name: Install Dependencies
      run: sfw pnpm install --frozen-lockfile

    - name: Build
      run: pnpm build

    - name: Testing
      run: pnpm test:ci

    - name: Publish
      run: pnpm publish --provenance --access public --no-git-checks
